const BUILDING_HOUSE="house";
const BUILDING_METERIAL="material";
const BUILDING_TREE="tree";
const BUILDING_CAR="car";
const BUILDING_ENTITYPARCEL="entityParcel"

export {BUILDING_HOUSE,BUILDING_METERIAL,BUILDING_TREE,BUILDING_CAR,BUILDING_ENTITYPARCEL}